version: '2'

services:
  orr-ont:
    image: mmisw/orr-ont:3.1.2
    container_name: orr-ont
    depends_on:
      - agraph
      - mongo

    ports:
      # host port can be changed as needed/desired
      - "9090:8080"

    volumes:
      # in general, no need to make adjustments here, expect perhaps for the host
      # part location corresponding to container's `/opt/orr-ont-base-directory`.
      - $PWD/orront.conf:/etc/orront.conf
      - $PWD/notifyemails:/etc/orront/notifyemails
      # NOTE: The following must be the same mapping as for the "agraph" service below
      - $PWD/orr_data:/opt/orr-ont-base-directory

    environment:
      # Not need to change the following unless of course the associated host names/ports are changed
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - AGRAPH_HOST=agraph
      - AGRAPH_PORT=10035

  agraph:
    image: franzinc/agraph
    container_name: agraph
    mem_limit: 1g

    ports:
      # host ports can be changed as needed/desired
      - "10000-10035:10000-10035"

    volumes:
      # NOTE: The following must be the same mapping as for the "orr-ont" service above
      - $PWD/orr_data:/opt/orr-ont-base-directory

  mongo:
    image: mongo
    container_name: mongo

    ports:
      # host port can be changed as needed/desired
      - "27017:27017"

    volumes:
      - $PWD/mongo_data:/data/db
